name: Build

on:
  workflow_call:
    inputs:
      username:
        required: false
        type: string

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install
        run: npm install

      - name: Build for deployment
        run: npm run dbuild

  store:
    name: Store
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Upload build
        uses: actions/upload-artifact@v3
        with:
          name: latest-build
          path: build/
