name: dbuild
on: [push]
jobs:
  ng-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "16"
        
      - name: Install
        run: npm install

      - name: Build for deployment        
        run: npm run dbuild
      
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: docs
          folder: build
      