name: Deploy

on:
  workflow_call:
    inputs:
      username:
        required: false
        type: string

jobs:
  deploy:
    name: Download and deploy
    runs-on: ubuntu-latest
    steps:
      - name: Download build
        uses: actions/download-artifact@v3
        with:
          name: latest-build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build
          branch: build
