name: Deploy

on:
  workflow_call:
    inputs:
      username:
        required: false
        type: string

jobs:
  download:
    name: Download
    runs-on: ubuntu-latest
    steps:
      - name: Download build
        uses: actions/download-artifact@v3
        with:
          name: latest-build

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: latest-build
          branch: build
