name: Deploy

on:
  workflow_call:
    inputs:
      username:
        required: false
        type: string

jobs:
  download:
    name: Download > Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Download build
        uses: actions/download-artifact@v3
        with:
          name: build

      - name: command
        run: ls -l

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build
          branch: build
