name: Build

on:
  workflow_call:
    inputs:
      username:
        required: false
        type: string

jobs:
  build:
    name: Deploy latest build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build
          branch: build
