name: Store build

on:
  workflow_call:
    inputs:
      username:
        required: false
        type: string

jobs:
  store:
    name: Store build
    runs-on: ubuntu-latest
    steps:
      - name: Upload build
        uses: actions/upload-artifact@v3
        with:
          name: latest-build
          path: build
